-- Generated by scripts/generate-seed-sql.ts from packages/shared/src/seed/catalog.json. Do not edit by hand.
-- PRICES ARE PLACEHOLDERS until the owner sets them. Images resolve against the web app's /public folder.
begin;

insert into public.categories (slug, name, cut, sort_order) values
  ('tees', 'Tees', 'Tee', 0),
  ('oversized-tees', 'Oversized tees', 'Oversized tee', 1),
  ('tanks', 'Tanks', 'Tank', 2),
  ('hats', 'Hats', 'Cap', 3)
on conflict (slug) do update set name = excluded.name, cut = excluded.cut, sort_order = excluded.sort_order;

insert into public.collections (slug, name, family_code, pillar, story, scripture_ref, sort_order) values
  ('royal-heritage', 'Royal Heritage', 'R', 'Royal heritage', 'The throne of grace and a kingdom that cannot be shaken, carved in arches and ornament.', 'Hebrews 4:16', 0),
  ('broken-bond', 'Broken Bond', 'B', 'Freedom', 'Chains broken and death without dominion. Stand firm in what was won.', 'Galatians 5:1', 1),
  ('rolled-away', 'Rolled Away', 'T', 'Resurrection', 'The stone rolled away and the tomb empty at dawn. New life, worn plainly.', 'Luke 24:1–6', 2)
on conflict (slug) do update set name = excluded.name, family_code = excluded.family_code, pillar = excluded.pillar, story = excluded.story, scripture_ref = excluded.scripture_ref, sort_order = excluded.sort_order;

insert into public.products (code, slug, name, collection_slug, category_slug, price_cents, currency, scripture_ref,
  story_art, story_front, story_back, story_inks, story_paraphrase, story_fit, story_material, featured, released_at) values
  ('A3-T02', 'third-morning', 'Third Morning', 'rolled-away', 'oversized-tees', 4400, 'USD', 'Luke 24:1–6', 'The tomb stands open at dawn, the stone rolled back and light spilling from the doorway beneath the wordmark.', 'Small Thorn Cross, left chest, bone ink', 'Thornbound wordmark over the open tomb, rolled stone and rising sun', 'Bone, dawn gold', 'At dawn the women found the stone moved and the tomb empty. He had risen.', 'Oversized tee · dropped shoulder, boxy body', null, true, '2026-09-20'),
  ('A3-B01', 'shattered-dominion', 'Shattered Dominion', 'broken-bond', 'oversized-tees', 4400, 'USD', 'Romans 6:9', 'A ring of rusted chain breaks apart around the Thorn Cross, its links falling loose beneath the wordmark.', 'Small Thorn Cross, left chest, bone ink', 'Thornbound wordmark over a ring of breaking chain around the Thorn Cross', 'Bone, copper', 'Christ was raised and will never die again. Death has no hold on him.', 'Oversized tee · dropped shoulder, boxy body', null, true, '2026-08-14'),
  ('A3-R01', 'throne-of-grace', 'Throne of Grace', 'royal-heritage', 'oversized-tees', 4400, 'USD', 'Hebrews 4:16', 'A carved arch frames the Thorn Cross above the wordmark, with olive branches gathered at its foot.', 'Small Thorn Cross, left chest, bone ink', 'Gothic arch, Thorn Cross and olive branches around the wordmark', 'Bone, oxblood', 'Come boldly to the throne of grace and find mercy and help when you need it.', 'Oversized tee · dropped shoulder, boxy body', null, true, '2026-07-10'),
  ('A3-B02', 'freed-in-awe', 'Freed in Awe', 'broken-bond', 'tees', 3800, 'USD', 'Galatians 5:1', 'Open shackles hang beneath the wordmark, the chain between them snapped clean.', 'Thornbound wordmark, small, center chest', 'Open shackles and a snapped chain under the wordmark', 'Bone, copper', 'Christ set us free so that we would stay free. Stand firm.', 'Tee · regular fit', null, true, '2026-08-14'),
  ('A3-T01', 'stone-rolled-aside', 'Stone Rolled Aside', 'rolled-away', 'tees', 3800, 'USD', 'Mark 16:4', 'A great round stone rests beside an open tomb, morning light behind it.', 'Small Thorn Cross, left chest, coal ink', 'The rolled stone and open tomb under the wordmark', 'Coal, dawn gold', 'They looked up and saw the heavy stone already rolled aside.', 'Tee · regular fit', null, false, '2026-09-20'),
  ('A3-R02', 'unshaken-kingdom', 'Unshaken Kingdom', 'royal-heritage', 'tees', 3800, 'USD', 'Hebrews 12:28', 'Twin columns rise into an unbroken arch, a thorn vine running along the keystone.', 'Small Thorn Cross, left chest, bone ink', 'Columns and arch with a thorn vine above the wordmark', 'Bone, muted gold', 'We are receiving a kingdom that cannot be shaken, so we worship with awe.', 'Tee · regular fit', null, false, '2026-07-10'),
  ('A3-B03', 'chains-snapped', 'Chains Snapped', 'broken-bond', 'tanks', 3400, 'USD', 'Psalm 107:14', 'A single chain splits at its center link, both halves falling away from a lily.', 'Thornbound wordmark, small, center chest', 'Split chain and lily under the wordmark', 'Bone, copper', 'He led them out of darkness and deep gloom and snapped their chains.', 'Tank · relaxed armhole, straight hem', null, false, '2026-08-14'),
  ('A3-T03', 'he-is-risen', 'He Is Risen', 'rolled-away', 'tanks', 3400, 'USD', 'Matthew 28:6', 'Lilies rise from the threshold of an empty tomb.', 'Small Thorn Cross, left chest, coal ink', 'Lilies at the tomb''s threshold under the wordmark', 'Coal, moss', 'He is not here. He has risen, just as he said he would.', 'Tank · relaxed armhole, straight hem', null, false, '2026-09-20'),
  ('A3-H01', 'thornbound-cap', 'Thornbound Cap', 'broken-bond', 'hats', 3200, 'USD', '2 Corinthians 3:17', 'The small Thorn Cross, embroidered in bone thread on the front panel.', 'Embroidered Thorn Cross, front panel, bone thread', 'Small embroidered wordmark above the strap', 'Bone thread', 'Where the Spirit of the Lord is, there is freedom.', 'Cap · unstructured six-panel, adjustable strap', null, false, '2026-08-14'),
  ('A3-H02', 'kingdom-cap', 'Kingdom Cap', 'royal-heritage', 'hats', 3200, 'USD', 'Psalm 145:13', 'A thorn wreath embroidered in bone thread on the front panel.', 'Embroidered thorn wreath, front panel, bone thread', 'Small embroidered wordmark above the strap', 'Bone thread', 'His kingdom is everlasting. He rules through every generation.', 'Cap · unstructured six-panel, adjustable strap', null, false, '2026-07-10')
on conflict (code) do update set slug = excluded.slug, name = excluded.name, collection_slug = excluded.collection_slug, category_slug = excluded.category_slug, price_cents = excluded.price_cents, scripture_ref = excluded.scripture_ref, story_art = excluded.story_art, story_front = excluded.story_front, story_back = excluded.story_back, story_inks = excluded.story_inks, story_paraphrase = excluded.story_paraphrase, story_fit = excluded.story_fit, story_material = excluded.story_material, featured = excluded.featured, released_at = excluded.released_at;

insert into public.product_variants (product_id, sku, color_name, color_token, color_rank, size, size_rank, available)
select p.id, v.sku, v.color_name, v.color_token, v.color_rank, v.size, v.size_rank, v.available
from (values
  ('A3-T02', 'A3-T02-WASHED-COAL-S', 'Washed coal', 'garment-washed-coal', 0, 'S', 1, true),
  ('A3-T02', 'A3-T02-WASHED-COAL-M', 'Washed coal', 'garment-washed-coal', 0, 'M', 2, true),
  ('A3-T02', 'A3-T02-WASHED-COAL-L', 'Washed coal', 'garment-washed-coal', 0, 'L', 3, true),
  ('A3-T02', 'A3-T02-WASHED-COAL-XL', 'Washed coal', 'garment-washed-coal', 0, 'XL', 4, true),
  ('A3-T02', 'A3-T02-WASHED-COAL-2XL', 'Washed coal', 'garment-washed-coal', 0, '2XL', 5, true),
  ('A3-T02', 'A3-T02-FADED-BLACK-S', 'Faded black', 'garment-faded-black', 1, 'S', 1, true),
  ('A3-T02', 'A3-T02-FADED-BLACK-M', 'Faded black', 'garment-faded-black', 1, 'M', 2, true),
  ('A3-T02', 'A3-T02-FADED-BLACK-L', 'Faded black', 'garment-faded-black', 1, 'L', 3, true),
  ('A3-T02', 'A3-T02-FADED-BLACK-XL', 'Faded black', 'garment-faded-black', 1, 'XL', 4, true),
  ('A3-T02', 'A3-T02-FADED-BLACK-2XL', 'Faded black', 'garment-faded-black', 1, '2XL', 5, false),
  ('A3-B01', 'A3-B01-FADED-BLACK-S', 'Faded black', 'garment-faded-black', 0, 'S', 1, true),
  ('A3-B01', 'A3-B01-FADED-BLACK-M', 'Faded black', 'garment-faded-black', 0, 'M', 2, true),
  ('A3-B01', 'A3-B01-FADED-BLACK-L', 'Faded black', 'garment-faded-black', 0, 'L', 3, true),
  ('A3-B01', 'A3-B01-FADED-BLACK-XL', 'Faded black', 'garment-faded-black', 0, 'XL', 4, true),
  ('A3-B01', 'A3-B01-FADED-BLACK-2XL', 'Faded black', 'garment-faded-black', 0, '2XL', 5, true),
  ('A3-B01', 'A3-B01-WASHED-COAL-S', 'Washed coal', 'garment-washed-coal', 1, 'S', 1, true),
  ('A3-B01', 'A3-B01-WASHED-COAL-M', 'Washed coal', 'garment-washed-coal', 1, 'M', 2, true),
  ('A3-B01', 'A3-B01-WASHED-COAL-L', 'Washed coal', 'garment-washed-coal', 1, 'L', 3, true),
  ('A3-B01', 'A3-B01-WASHED-COAL-XL', 'Washed coal', 'garment-washed-coal', 1, 'XL', 4, true),
  ('A3-B01', 'A3-B01-WASHED-COAL-2XL', 'Washed coal', 'garment-washed-coal', 1, '2XL', 5, true),
  ('A3-R01', 'A3-R01-WASHED-COAL-S', 'Washed coal', 'garment-washed-coal', 0, 'S', 1, true),
  ('A3-R01', 'A3-R01-WASHED-COAL-M', 'Washed coal', 'garment-washed-coal', 0, 'M', 2, true),
  ('A3-R01', 'A3-R01-WASHED-COAL-L', 'Washed coal', 'garment-washed-coal', 0, 'L', 3, true),
  ('A3-R01', 'A3-R01-WASHED-COAL-XL', 'Washed coal', 'garment-washed-coal', 0, 'XL', 4, true),
  ('A3-R01', 'A3-R01-WASHED-COAL-2XL', 'Washed coal', 'garment-washed-coal', 0, '2XL', 5, true),
  ('A3-B02', 'A3-B02-WASHED-COAL-S', 'Washed coal', 'garment-washed-coal', 0, 'S', 1, true),
  ('A3-B02', 'A3-B02-WASHED-COAL-M', 'Washed coal', 'garment-washed-coal', 0, 'M', 2, true),
  ('A3-B02', 'A3-B02-WASHED-COAL-L', 'Washed coal', 'garment-washed-coal', 0, 'L', 3, true),
  ('A3-B02', 'A3-B02-WASHED-COAL-XL', 'Washed coal', 'garment-washed-coal', 0, 'XL', 4, true),
  ('A3-B02', 'A3-B02-WASHED-COAL-2XL', 'Washed coal', 'garment-washed-coal', 0, '2XL', 5, true),
  ('A3-B02', 'A3-B02-WARM-BONE-S', 'Warm bone', 'garment-warm-bone', 1, 'S', 1, true),
  ('A3-B02', 'A3-B02-WARM-BONE-M', 'Warm bone', 'garment-warm-bone', 1, 'M', 2, true),
  ('A3-B02', 'A3-B02-WARM-BONE-L', 'Warm bone', 'garment-warm-bone', 1, 'L', 3, true),
  ('A3-B02', 'A3-B02-WARM-BONE-XL', 'Warm bone', 'garment-warm-bone', 1, 'XL', 4, true),
  ('A3-B02', 'A3-B02-WARM-BONE-2XL', 'Warm bone', 'garment-warm-bone', 1, '2XL', 5, true),
  ('A3-T01', 'A3-T01-WARM-BONE-S', 'Warm bone', 'garment-warm-bone', 0, 'S', 1, true),
  ('A3-T01', 'A3-T01-WARM-BONE-M', 'Warm bone', 'garment-warm-bone', 0, 'M', 2, true),
  ('A3-T01', 'A3-T01-WARM-BONE-L', 'Warm bone', 'garment-warm-bone', 0, 'L', 3, true),
  ('A3-T01', 'A3-T01-WARM-BONE-XL', 'Warm bone', 'garment-warm-bone', 0, 'XL', 4, true),
  ('A3-T01', 'A3-T01-WARM-BONE-2XL', 'Warm bone', 'garment-warm-bone', 0, '2XL', 5, true),
  ('A3-T01', 'A3-T01-WASHED-SAND-S', 'Washed sand', 'garment-washed-sand', 1, 'S', 1, true),
  ('A3-T01', 'A3-T01-WASHED-SAND-M', 'Washed sand', 'garment-washed-sand', 1, 'M', 2, true),
  ('A3-T01', 'A3-T01-WASHED-SAND-L', 'Washed sand', 'garment-washed-sand', 1, 'L', 3, true),
  ('A3-T01', 'A3-T01-WASHED-SAND-XL', 'Washed sand', 'garment-washed-sand', 1, 'XL', 4, true),
  ('A3-T01', 'A3-T01-WASHED-SAND-2XL', 'Washed sand', 'garment-washed-sand', 1, '2XL', 5, true),
  ('A3-R02', 'A3-R02-WASHED-DEEP-PLUM-S', 'Washed deep plum', 'garment-washed-deep-plum', 0, 'S', 1, true),
  ('A3-R02', 'A3-R02-WASHED-DEEP-PLUM-M', 'Washed deep plum', 'garment-washed-deep-plum', 0, 'M', 2, true),
  ('A3-R02', 'A3-R02-WASHED-DEEP-PLUM-L', 'Washed deep plum', 'garment-washed-deep-plum', 0, 'L', 3, true),
  ('A3-R02', 'A3-R02-WASHED-DEEP-PLUM-XL', 'Washed deep plum', 'garment-washed-deep-plum', 0, 'XL', 4, true),
  ('A3-R02', 'A3-R02-WASHED-DEEP-PLUM-2XL', 'Washed deep plum', 'garment-washed-deep-plum', 0, '2XL', 5, true),
  ('A3-R02', 'A3-R02-FADED-BLACK-S', 'Faded black', 'garment-faded-black', 1, 'S', 1, true),
  ('A3-R02', 'A3-R02-FADED-BLACK-M', 'Faded black', 'garment-faded-black', 1, 'M', 2, true),
  ('A3-R02', 'A3-R02-FADED-BLACK-L', 'Faded black', 'garment-faded-black', 1, 'L', 3, true),
  ('A3-R02', 'A3-R02-FADED-BLACK-XL', 'Faded black', 'garment-faded-black', 1, 'XL', 4, true),
  ('A3-R02', 'A3-R02-FADED-BLACK-2XL', 'Faded black', 'garment-faded-black', 1, '2XL', 5, true),
  ('A3-B03', 'A3-B03-WASHED-GRAPHITE-S', 'Washed graphite', 'garment-washed-graphite', 0, 'S', 1, false),
  ('A3-B03', 'A3-B03-WASHED-GRAPHITE-M', 'Washed graphite', 'garment-washed-graphite', 0, 'M', 2, true),
  ('A3-B03', 'A3-B03-WASHED-GRAPHITE-L', 'Washed graphite', 'garment-washed-graphite', 0, 'L', 3, true),
  ('A3-B03', 'A3-B03-WASHED-GRAPHITE-XL', 'Washed graphite', 'garment-washed-graphite', 0, 'XL', 4, true),
  ('A3-B03', 'A3-B03-WASHED-GRAPHITE-2XL', 'Washed graphite', 'garment-washed-graphite', 0, '2XL', 5, true),
  ('A3-B03', 'A3-B03-FADED-BLACK-S', 'Faded black', 'garment-faded-black', 1, 'S', 1, true),
  ('A3-B03', 'A3-B03-FADED-BLACK-M', 'Faded black', 'garment-faded-black', 1, 'M', 2, true),
  ('A3-B03', 'A3-B03-FADED-BLACK-L', 'Faded black', 'garment-faded-black', 1, 'L', 3, true),
  ('A3-B03', 'A3-B03-FADED-BLACK-XL', 'Faded black', 'garment-faded-black', 1, 'XL', 4, true),
  ('A3-B03', 'A3-B03-FADED-BLACK-2XL', 'Faded black', 'garment-faded-black', 1, '2XL', 5, true),
  ('A3-T03', 'A3-T03-WASHED-SAND-S', 'Washed sand', 'garment-washed-sand', 0, 'S', 1, true),
  ('A3-T03', 'A3-T03-WASHED-SAND-M', 'Washed sand', 'garment-washed-sand', 0, 'M', 2, true),
  ('A3-T03', 'A3-T03-WASHED-SAND-L', 'Washed sand', 'garment-washed-sand', 0, 'L', 3, true),
  ('A3-T03', 'A3-T03-WASHED-SAND-XL', 'Washed sand', 'garment-washed-sand', 0, 'XL', 4, true),
  ('A3-T03', 'A3-T03-WASHED-SAND-2XL', 'Washed sand', 'garment-washed-sand', 0, '2XL', 5, true),
  ('A3-T03', 'A3-T03-WASHED-DEEP-OLIVE-S', 'Washed deep olive', 'garment-washed-deep-olive', 1, 'S', 1, true),
  ('A3-T03', 'A3-T03-WASHED-DEEP-OLIVE-M', 'Washed deep olive', 'garment-washed-deep-olive', 1, 'M', 2, true),
  ('A3-T03', 'A3-T03-WASHED-DEEP-OLIVE-L', 'Washed deep olive', 'garment-washed-deep-olive', 1, 'L', 3, true),
  ('A3-T03', 'A3-T03-WASHED-DEEP-OLIVE-XL', 'Washed deep olive', 'garment-washed-deep-olive', 1, 'XL', 4, true),
  ('A3-T03', 'A3-T03-WASHED-DEEP-OLIVE-2XL', 'Washed deep olive', 'garment-washed-deep-olive', 1, '2XL', 5, true),
  ('A3-H01', 'A3-H01-WASHED-BLACK-TWILL-ONE-SIZE', 'Washed black twill', 'cap-washed-black-twill', 0, 'One size', 7, true),
  ('A3-H01', 'A3-H01-WASHED-CHARCOAL-TWILL-ONE-SIZE', 'Washed charcoal twill', 'cap-washed-charcoal-twill', 1, 'One size', 7, true),
  ('A3-H02', 'A3-H02-OXBLOOD-CORDUROY-ONE-SIZE', 'Oxblood corduroy', 'cap-oxblood-corduroy', 0, 'One size', 7, true),
  ('A3-H02', 'A3-H02-SANDSTONE-ONE-SIZE', 'Sandstone', 'cap-sandstone', 1, 'One size', 7, true)
) as v (code, sku, color_name, color_token, color_rank, size, size_rank, available)
join public.products p on p.code = v.code
on conflict (sku) do update set color_name = excluded.color_name, color_token = excluded.color_token, color_rank = excluded.color_rank, size = excluded.size,
  size_rank = excluded.size_rank, available = excluded.available;

delete from public.product_images where product_id in (select id from public.products where code in ('A3-T02', 'A3-B01', 'A3-R01', 'A3-B02', 'A3-T01', 'A3-R02', 'A3-B03', 'A3-T03', 'A3-H01', 'A3-H02'));
insert into public.product_images (product_id, url, alt, view, sort_order)
select p.id, i.url, i.alt, i.view, i.sort_order
from (values
  ('A3-T02', '/products/a3-t02-back.jpg', 'Third Morning back print: the open tomb at dawn with the stone rolled aside', 'back', 0),
  ('A3-T02', '/products/a3-t02-front.svg', 'Third Morning front: small Thorn Cross on the left chest (sample art)', 'front', 1),
  ('A3-B01', '/products/a3-b01-back.jpg', 'Shattered Dominion back print: a ring of breaking chain around the cross', 'back', 0),
  ('A3-B01', '/products/a3-b01-front.svg', 'Shattered Dominion front: small Thorn Cross on the left chest (sample art)', 'front', 1),
  ('A3-R01', '/products/a3-r01-back.jpg', 'Throne of Grace back print: a carved arch framing the cross above olive branches', 'back', 0),
  ('A3-R01', '/products/a3-r01-front.svg', 'Throne of Grace front: small Thorn Cross on the left chest (sample art)', 'front', 1),
  ('A3-B02', '/products/a3-b02-back.svg', 'Freed in Awe back: the wordmark above a copper thorn wreath (sample art)', 'back', 0),
  ('A3-B02', '/products/a3-b02-front.svg', 'Freed in Awe in warm bone, front: small wordmark on the chest (sample art)', 'front', 1),
  ('A3-T01', '/products/a3-t01-back.svg', 'Stone Rolled Aside back: the wordmark above a lily (sample art)', 'back', 0),
  ('A3-T01', '/products/a3-t01-front.svg', 'Stone Rolled Aside in washed sand, front: small Thorn Cross (sample art)', 'front', 1),
  ('A3-R02', '/products/a3-r02-back.svg', 'Unshaken Kingdom back: the wordmark above a gold Thorn Cross (sample art)', 'back', 0),
  ('A3-R02', '/products/a3-r02-front.svg', 'Unshaken Kingdom in faded black, front: small Thorn Cross (sample art)', 'front', 1),
  ('A3-B03', '/products/a3-b03-back.svg', 'Chains Snapped back: the wordmark above a thorn vine (sample art)', 'back', 0),
  ('A3-B03', '/products/a3-b03-front.svg', 'Chains Snapped in faded black, front: small wordmark on the chest (sample art)', 'front', 1),
  ('A3-T03', '/products/a3-t03-back.svg', 'He Is Risen back: the wordmark above a lily (sample art)', 'back', 0),
  ('A3-T03', '/products/a3-t03-front.svg', 'He Is Risen in washed deep olive, front: small Thorn Cross (sample art)', 'front', 1),
  ('A3-H01', '/products/a3-h01-back.svg', 'Thornbound Cap in washed black twill with an embroidered Thorn Cross (sample art)', 'back', 0),
  ('A3-H01', '/products/a3-h01-front.svg', 'Thornbound Cap in washed charcoal twill (sample art)', 'front', 1),
  ('A3-H02', '/products/a3-h02-back.svg', 'Kingdom Cap in oxblood corduroy with an embroidered thorn wreath (sample art)', 'back', 0),
  ('A3-H02', '/products/a3-h02-front.svg', 'Kingdom Cap in sandstone (sample art)', 'front', 1)
) as i (code, url, alt, view, sort_order)
join public.products p on p.code = i.code;

commit;
