// Regenerates src/marks/paths.ts from the single-path SVGs in assets/. Run: node scripts/extract-paths.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const marks = {
  WORDMARK: "assets/logos/awebound-wordmark.svg",
  THORN_CROSS: "assets/logos/thorn-cross.svg",
  THORN_CROSS_SMALL: "assets/logos/thorn-cross-small.svg",
  LILY: "assets/marks/lily.svg",
  THORN_VINE: "assets/marks/thorn-vine.svg",
  THORN_WREATH: "assets/marks/thorn-wreath.svg",
  THORN_RULE: "assets/marks/thorn-rule.svg",
};

let out =
  "// Generated by scripts/extract-paths.mjs from the brand SVGs. Do not edit by hand.\n" +
  "export interface MarkGeometry {\n  viewBox: string;\n  d: string;\n}\n\n";
for (const [name, file] of Object.entries(marks)) {
  const svg = readFileSync(join(root, file), "utf8");
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1];
  const paths = [...svg.matchAll(/\sd="([^"]+)"/g)].map((m) => m[1]);
  if (!viewBox || paths.length !== 1) throw new Error(`${file}: expected one path and a viewBox`);
  out += `export const ${name}: MarkGeometry = {\n  viewBox: ${JSON.stringify(viewBox)},\n  d: ${JSON.stringify(paths[0])},\n};\n\n`;
}
writeFileSync(join(root, "src/marks/paths.ts"), out.trimEnd() + "\n");
console.info("wrote src/marks/paths.ts");
