// Writes supabase/seed.sql from the sample catalog in packages/shared/src/seed/catalog.json,
// so the database and the API's offline seed mode always hold the same products.
// Run from the repo root: pnpm db:seed
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { SIZE_ORDER } from "../packages/shared/src/catalog";
import { seedCatalog } from "../packages/shared/src/seed/index";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const q = (value: string | null | undefined): string =>
  value === null || value === undefined ? "null" : `'${value.replace(/'/g, "''")}'`;
const b = (value: boolean): string => (value ? "true" : "false");
const sizeRank = (size: string): number => (SIZE_ORDER as readonly string[]).indexOf(size);

const { categories, collections, products } = seedCatalog;
const lines: string[] = [];

lines.push(
  "-- Generated by scripts/generate-seed-sql.ts from packages/shared/src/seed/catalog.json. Do not edit by hand.",
  "-- PRICES ARE PLACEHOLDERS until the owner sets them. Images resolve against the web app's /public folder.",
  "begin;",
  "",
);

lines.push("insert into public.categories (slug, name, cut, sort_order) values");
lines.push(
  categories.map((c, i) => `  (${q(c.slug)}, ${q(c.name)}, ${q(c.cut)}, ${i})`).join(",\n") +
    "\non conflict (slug) do update set name = excluded.name, cut = excluded.cut, sort_order = excluded.sort_order;",
  "",
);

lines.push("insert into public.collections (slug, name, family_code, pillar, story, scripture_ref, sort_order) values");
lines.push(
  collections
    .map((c, i) => `  (${q(c.slug)}, ${q(c.name)}, ${q(c.familyCode)}, ${q(c.pillar)}, ${q(c.story)}, ${q(c.scriptureRef)}, ${i})`)
    .join(",\n") +
    "\non conflict (slug) do update set name = excluded.name, family_code = excluded.family_code, pillar = excluded.pillar," +
    " story = excluded.story, scripture_ref = excluded.scripture_ref, sort_order = excluded.sort_order;",
  "",
);

lines.push(
  "insert into public.products (code, slug, name, collection_slug, category_slug, price_cents, currency, scripture_ref,",
  "  story_art, story_front, story_back, story_inks, story_paraphrase, story_fit, story_material, featured, released_at) values",
);
lines.push(
  products
    .map((p) =>
      [
        q(p.code),
        q(p.slug),
        q(p.name),
        q(p.collection.slug),
        q(p.category.slug),
        String(p.priceCents),
        q(p.currency),
        q(p.scriptureRef),
        q(p.story.art),
        q(p.story.front),
        q(p.story.back),
        q(p.story.inks),
        q(p.story.paraphrase),
        q(p.story.fit),
        q(p.story.material),
        b(p.featured),
        q(p.releasedAt),
      ].join(", "),
    )
    .map((row) => `  (${row})`)
    .join(",\n") +
    "\non conflict (code) do update set slug = excluded.slug, name = excluded.name, collection_slug = excluded.collection_slug," +
    " category_slug = excluded.category_slug, price_cents = excluded.price_cents, scripture_ref = excluded.scripture_ref," +
    " story_art = excluded.story_art, story_front = excluded.story_front, story_back = excluded.story_back," +
    " story_inks = excluded.story_inks, story_paraphrase = excluded.story_paraphrase, story_fit = excluded.story_fit," +
    " story_material = excluded.story_material, featured = excluded.featured, released_at = excluded.released_at;",
  "",
);

lines.push(
  "insert into public.product_variants (product_id, sku, color_name, color_token, size, size_rank, available)",
  "select p.id, v.sku, v.color_name, v.color_token, v.size, v.size_rank, v.available",
  "from (values",
);
lines.push(
  products
    .flatMap((p) =>
      p.variants.map((v) => {
        const token = p.colors.find((c) => c.name === v.color)?.token ?? "";
        return `  (${q(p.code)}, ${q(v.sku)}, ${q(v.color)}, ${q(token)}, ${q(v.size)}, ${sizeRank(v.size)}, ${b(v.available)})`;
      }),
    )
    .join(",\n"),
);
lines.push(
  ") as v (code, sku, color_name, color_token, size, size_rank, available)",
  "join public.products p on p.code = v.code",
  "on conflict (sku) do update set color_name = excluded.color_name, color_token = excluded.color_token, size = excluded.size,",
  "  size_rank = excluded.size_rank, available = excluded.available;",
  "",
);

lines.push(
  "delete from public.product_images where product_id in (select id from public.products where code in (" +
    products.map((p) => q(p.code)).join(", ") +
    "));",
  "insert into public.product_images (product_id, url, alt, view, sort_order)",
  "select p.id, i.url, i.alt, i.view, i.sort_order",
  "from (values",
);
lines.push(
  products
    .flatMap((p) => p.images.map((img, i) => `  (${q(p.code)}, ${q(img.url)}, ${q(img.alt)}, ${q(img.view)}, ${i})`))
    .join(",\n"),
);
lines.push(") as i (code, url, alt, view, sort_order)", "join public.products p on p.code = i.code;", "", "commit;", "");

const target = join(root, "supabase/seed.sql");
writeFileSync(target, lines.join("\n"));
console.info(`wrote ${target} (${products.length} products, ${products.reduce((n, p) => n + p.variants.length, 0)} variants)`);
